esphome/esphome-devices

_devices/Sonoff-S31/Sonoff-S31.md

The power sensors could not provide reliable data with more than 1 decimal place, and would flood Home Assistant with state change events when there are 10s of these devices.

Avoid flooding Home Assistant with updates from s31 power sensors

---

_devices/Gosund-WP3/Gosund-WP3.md

- Updated pinout table to contain blue led (`GPIO13`)
- Updated configuration to toggle `GPIO13` when relay is toggled, which is the stock firmware behavior.

Gosund WP3: Add Support For Blue LED

---

_devices/Shelly-Plug-S/Shelly-Plug-S.md

From @dsander at https://github.com/jonathanadams/esphome-configs/pull/162:
> Use `power` as the `id` instead of  `vermogen` to fix the reference used in `total_daily_energy` sensor.
(had to submit this twice because I deleted the `master` branch in favor of `main`)

Retarget PR: "Fix typo in Shelly Plug S example configuration"

---

_devices/POWRUI-AHR-079/POWRUI-AHR-079.md

Add config for [POWRUI AHR-079](https://www.amazon.com/gp/product/B07RL56DPD)
- Buttons locally control their associated relays
- Relays are exposed as ${friendlyName} Outlet X
GPIO mapping from [Powrui AHR-079 Power Strip Template for Tasmota](https://templates.blakadder.com/powrui_AHR-079.html)
Duped from [Add POWRUI AHR-079 Power Strip by markschabacker · Pull Request #146 · jonathanadams/esphome-configs](https://github.com/jonathanadams/esphome-configs/pull/146)

Add POWRUI AHR-079 Power Strip

---

_devices/Feit-BPA800-RGBW-AG-2(P)/Feit-BPA800-RGBW-AG-2(P).md

Added a new Feit RGBWW variant. [This one](https://templates.blakadder.com/feit_electric-BPA800RGBWAG2P.html) appears to have _internal_ gamma correction, so it specifically has it omitted. I tested the color matching wheel before and after, and it definitely seems more accurate with `gamma_correction: 0.0` set.

Add Feit BPA800/RGBW/AG/2(P)

---

_devices/BlitzWolf-BW-SHP6/BlitzWolf-BW-SHP6.md

Apparently, Blitzwolf has slightly modified this device by changing the power
monitoring HLW8012 CF1 pin.
Calibration values are also different.
Signed-off-by: Álvaro Fernández Rojas <noltari@gmail.com>

BW-SHP6: document 2020 model

---

_devices/Arlec-PC189HA-Plug/Arlec-PC189HA-Plug.md

INPUT_PULLUP went missing when copying the sample over the the repo from my own device config

Fix PC189HA example

---

_devices/ESP32-CAM/ESP32-CAM.md

It's possible to define ESP32-CAM LED as PWM, but to do so we need to use PWM channel 2, since channel 1 is used by the camera.

ESP32-CAM: switch to PWM LED

---

src/docs/devices/Feit-BPA800-RGBW-AG-2(P)/index.md
src/docs/devices/Feit-BPA800-RGBW-AG-2/index.md

I'm the original submitter of the `2(P)` bulb docs, and I have some of the `2`, non-`(P)` bulbs as well. This is fully tested by me for both.

Fix and differentiate two similar model bulbs

---

src/docs/devices/BlitzWolf-BW-SHP3/index.md

Similar to the SHP2, but is apparently a US-only variant with two side-by-side outlets, each independently controllable. This has been fully tested by me and works with all buttons and LEDs behaving as one would expect.

Add BlitzWolf-SHP3

---

src/docs/devices/TreatLife-DS03/index.md

DS03 has four fan speeds, default is three.

Add full support for DS03 speed levels

---

src/docs/devices/LSC-Smart-Connect-Switch/index.md

- Wrong GPIO14 was used for button. Correct is GPIO13.
- Simplified/corrected code
- Using button on plug itself now switches relay and statusled correctly

Update index.md for LSC Power Plug

---

src/docs/devices/Shelly-25/index.md

- Prevent overheating by setting IRQ pin on ADE7953 sensor as described by [the ade7953 documentation](https://esphome.io/components/sensor/ade7953.html)
- Enable wifi power_save_mode (saves energy and reduces heat generation, improve lifespan) HIGH/LOW are mixed up esphome/issues/issues/1532

Improve Shelly 2.5 config

---

src/docs/devices/DETA-Grid-Connect-Smart-Switch/index.md

Deta/Bunnings now selling these switches with incompatible ESP chip (WB3S). Including this in documentation as a warning.

Product now ships with incompatible WB3S chip

---

src/docs/devices/MagicHome-ZJ-WFMN-A-RGBW/index.md

Warning about version 1.2 of PCB that uses BL602 instead of ESP.

New chip BL602 used instead of ESP for MagicHome devices

---

src/docs/devices/DETA-Grid-Connect-Smart-Switch/index.md

As per this comment, https://github.com/esphome/issues/issues/2675#issuecomment-959002147, 
set GPIO16 to mode: INPUT as INPUT_PULLUP is not supported.

Set GPIO16 to mode: INPUT

---

src/docs/devices/Aukey-SH-PA1-Smart-Plug/index.md

The same pin should **not** be used for both an input and an output at the same time. 
Utilize ESPHome automations correctly to trigger another light/relay to follow state.
See esphome/issues#2865

Fix template that uses binary sensor on output pin

---

src/docs/devices/TreatLife-DS02S/index.md

Update docs to reflect that newer Treatlife DS02S devices require a baudrate of 115200 instead of the aforementioned 9600 baudrate.

Treatlife DS02S uses baudrate 115200

---

src/docs/devices/Gosund-SP1/index.md

After reboot the fakebutton was always "off" even if the relay was "on".
Using the normal "switch" keeps the state even after reboot

Bugfix: Wrong "Power Switch" state after reboot

---

src/docs/devices/Gosund-WO1/index.md

In measuring values from multiple devices, I decided to adjust the voltage divider to the average of the observed range, and add a general notes section describing it may need to be adjusted.

Gosund WO1 adjustments

---

src/docs/devices/Nameless-DS-102/index.md

As of May 2022 these switches use a WB3S chip (BK7231T) and are no longer compatible.

DS-102 uses WB3S (non esp chips) now

---

src/docs/devices/Sonoff-S31/index.md

This adds a blurb about putting it into bootloader mode, as well as a comment about using `api:`.
This also adds `restore_mode`, as I imagine most people want their devices to re-power up after e.g. a power outage.

sonoff-s31: Update docs

---

src/docs/devices/Gosund-SP112/index.md

as per gosund sp111 device, the 775 value for voltage divider gives a much better voltage aproximation. (in my case from  275 to 245 which is 99,5% accurate)

updated divider for voltage

---

src/docs/devices/Teckin-SP20/index.md

Based on my own units, and looking around (Tasmota doc pages) I was able to flash and configure my SP20 units using an alternative pinout. 
This PR includes this alternate pinout in the configuration page to support others that might have same unit model/revision as me.

Updating SP20 doc with alternative pinout

---

src/docs/devices/Shelly-EM/index.md

This PR adds a new configuration to use a Shelly EM as a whole-home energy monitor for 2-phase power.

Add Shelly EM configuration

---

src/docs/devices/Globe-4-Inch-9W-Downlight-50359/index.md

Disable power save mode to reduce pings from >1000ms to 2ms (default "light"). It seems either the WT32N-01N (or the ESP32-C3 specifically) require power save mode to be disabled.
Before:
```
Reply from 10.xx.xx.xx: bytes=32 time=101ms TTL=254
Reply from 10.xx.xx.xx: bytes=32 time=1236ms TTL=254
Reply from 10.xx.xx.xx: bytes=32 time=2ms TTL=254
Reply from 10.xx.xx.xx: bytes=32 time=106ms TTL=254
Request timed out.
Reply from 10.xx.xx.xx: bytes=32 time=3978ms TTL=254
Reply from 10.xx.xx.xx: bytes=32 time=4ms TTL=254
Reply from 10.xx.xx.xx: bytes=32 time=109ms TTL=254
Reply from 10.xx.xx.xx: bytes=32 time=1339ms TTL=254
Reply from 10.xx.xx.xx: bytes=32 time=2ms TTL=254
Reply from 10.xx.xx.xx: bytes=32 time=614ms TTL=254
Reply from 10.xx.xx.xx: bytes=32 time=1965ms TTL=254
```
After setting …

Modified wifi power save mode

---

src/docs/devices/Nous-A1t/index.md

I really appreciate this configuration, it got me started in no-time with my new device.
There were 2 things that disturbed me a bit:
1) When unplugging the Nous and plugging it in again, it did not retain the power status, it always started with power off.
2) The status LED was nice to have when plugging in the Nous, showing that it was seeking for WiFi etc. But when fully started, the LED was off and did not indicate the power status.

use status_led light platform; retain power status after power failure

---

src/docs/devices/Shelly-Plus-1/index.md
src/docs/devices/Shelly-Plus-1PM/index.md
src/docs/devices/Shelly-Plus-2PM/index.md

Confirmed on Shelly Plus 1 - the actual value of desoldered resistor is 10kOhm. The incorrect value seems to be obtained by in-circuit measurement which is affected by other components. After this fix the measured temperature is much closer to expected values.
While tested only on Shelly Plus 1, it is most probably applicable to other Shelly devices sharing the same design.

Shelly Plus - fix value of NTC voltage divider resistor

---

src/docs/devices/Mi-Desklamp-Pro/index.md

[fix] compilation error on aarch64 system (HomeAssistant on Raspberry Pi 4)

Update platform dependencies for Mi-Desklamp-Pro

---

src/docs/devices/Mi-Desklamp-Pro/index.md

- firmware now builds and runs successfully without runtime crash after boot due to single/multi-core build incompatibility.
- slight gamma correction applied to improve brightness control perception.
- default name changed from "Lights" to "Mi Desk Lamp Pro".
- reduced PWM frequency from 20kHz to 10kHz for better brightness control, however it may be debatable. 
- changed `restore_mode` from `ALWAYS_ON` to `RESTORE_DEFAULT_OFF`.

Fix runtime crash after boot on Mi-Desklamp-Pro

---

src/docs/devices/Kogan-Smarterhome-Smart-Plug-Energy-Meter-5v-24a-Usb-Ports/index.md

- Added a section about the plug revision I personally had purchased which seems different to what the original page author worked with (current/power values were quite off for me when using values from the template config file)
- Updated uptime human sensor to be more reliable as the current one after boot always results in one erroneous sensor update with a very high uptime value.

Update Kogan Plug docs

---

src/docs/devices/Orno-Single-Phase-Energy-meter-OR-WE-514/index.md

Values at adresses 0xA0xx are all U_DWORD

Corrected value types for modbus OR-WE-514 energy meter

---

src/docs/devices/Sonoff-BASIC-R2-v1.4/index.md

Looks like someone accidentally mixed up the UARTs GPIO pins.

Fix swapped UART GPIOs

---

src/docs/devices/Sonoff-S20/index.md

Active low, hence it needs to be inverted

Status led of Sonoff S20 is active low

---

src/docs/devices/Mi-Desklamp-1S/index.md

This PR changes the configuration to use the ESP-IDF framework as it properly supports single-core ESP32 chips in its upstream version.
However, this requires disabling the web server and the captive portal (https://github.com/esphome/feature-requests/issues/1649).
One issue with this config I've noticed is that the esphome dashboard shows the device as `offline`, however e.g. OTA updates work without issues.
I'm also not sure whether I should update the `date-published` in the front matter with this PR, as there is no separate `date-updated` field - let me know if that's the case.
Fixes #300 (hopefully).

Mi Desklamp 1S: use esp-idf framework

---

src/docs/devices/TreatLife-DS02S/index.md

I had the issue that was noted above in the 'notes', but I didnt read it an only copy and pasted the yaml file.  this adds some comments so you see the issue in the yaml file. I think all new DS02S 3 way wifi dimmer's require 115200.  Maybe we should go ahead and set the default to 115200 instead of making it a note.

Added notice to the baud_rate

---

src/docs/devices/Waveshare-epaper-cloud-module/index.md

Since the user button does a pull to gnd when pressed, the pin must be inverted and configured as input with pull up.
An adc is saturated at ~1.1 V. but since the battery voltage can be >4 V (and thus at the pin >1.33 V) the adc is saturated without attenuation and the battery voltage in correct.
With the initial programming I had problems to initialize the programming mode. The description to the initial programming with my procedure extended

Fix User Button pin settings / correct battery voltage measurement

---

src/docs/devices/Sonoff-S31/index.md

Update the basic example for Sonoff S31 status pin to be inverted

Update Sonoff S31 status pin to be inverted

---

src/docs/devices/Sonoff-S26/index.md

As of 2022.12 the syntax has changed. For me HA was requesting this change. The modified version works for me, so far.
Please merge this request.

Move board* to under esp8266 section

---

src/docs/devices/Sonoff-POW-Elite-16a/index.md

Add config example for Sonoff Pow Elite 16A (POWR320D) with all ESP sensors and Bluetooth proxy.
This model has a single relay in contrast to the  Sonoff Pow Elite 16A which has a bi-stable relay.

Sonoff POW Elite 16a (POWR316D) doc

---

src/docs/devices/Shelly-Plug-S/index.md

Plug is only rated for 10A
Only imposing a power limit is a safety risk.
A bad power factor can cause a power draw of less than the rated power but a current draw greater than 10A, risk of overheating or fire. Added the config to include a current limit.
Keeping power limit because this is handy to limit the power of some devices.

Add current limit

---

src/docs/devices/Mi-Desklamp-1S/index.md

This update is because on my lamp, the GPIO was inverted with the sign on the lamp

Update GPIO for Mi Desklamp 1S

---

src/docs/devices/TH3D-EZPlug-Plus/index.md

I discovered my previous config suffered a serious bounce of the relay if it was on upon reboot, resulting in many devices losing power in the process.  The addition of restore_from_flash and early_pin_init to the esp8266 configuration has successfully mitigated that in my testing.

Update TH3D-EZPlug-Plus to reduce relay bounce on restart

---

src/docs/devices/Gosund-SP111/index.md

In reference to `led_red` variable, the parts in its name were swapped. This was causing a compilation error.

Swap parts of `led_red` variable name

---

src/config/sidebar.yml
src/docs/adding-devices.md

TLDR; This pull request proposes a specification for expanding the tags options for the devices listed in this database
----
I submitted a [reddit post](https://www.reddit.com/r/Esphome/comments/12n0884/list_of_esphome_products/) looking for a sort of database of devices that were compatible with ESPHome. I've had a go at a modified spec for adding some extended attributes to the devices pages. In essence, it entails:
- board: the board type used in the project. At the moment I've just added esp8266 and esp32. Not sure if it needs to be more granular than that, open to feedback...
- project-url: so there's a nice holder to a link for the product or GitHub repo that contains the details about the project
- made-for-esphome: bool to capture if the manufacturer has conformed to the [made for …

Expanded tags definitions

---

src/docs/devices/Shelly-Plus-Plug-S/index.md

since we do have the "ESP32 RMT LED Strip" platform with esphome 2023.5, it is possible to address the LEDs when using the esp-idf framework. 
With this it is possible to use the plug as a bluetooth proxy too, because of the much smaller footprint.
Also added a switch in HA to lock the physical button.

changed framework to esp-idf

---

src/docs/devices/Sonoff-Mini-Relay/index.md

icon was throwing an error due to a spelling mistake

Update index.md to working icon format

---

src/docs/devices/Sonoff-S26/index.md

Causes compile time error as-is; compiles normally like this.

remove platform: in esphome section in Sonoff S26 example

---

src/docs/devices/TreatLife-DS02S/index.md

Add Advanced configuration for Treatlife DS02s devices. These devices have 3 dimming modes. This pull request adds documentation to the template to create a Tuya Select component.
Coming in the future when I figure out how to set a datapoint statically (or at least set it on boot), I will update this Advanced Configuration section with the required information as well.

Update Device: Treatlife DS02s to add Advanced Configuration Options

---

src/docs/devices/Sonoff-POW-Elite-20a/index.md

total_daily_energy sensor is fed by w_sensor (measured in W), but total_daily_energy is displayed in kWh.

Fix: total_daily_energy value

---

src/docs/devices/Sonoff-POW-Elite-20a/index.md

- lambda detached from template switch config in order to fix the unreliable button behavior
- lambda moved to a Load detection sensor
- set the template switch state to the actual relay state on boot

Fix: button instability

---

src/docs/devices/BlitzHome-BH-AP1/index.md

The filter reset tuya command needed to change from integer to boolean.

BlitzHome BH-AP1 filter reset fix.

---

src/docs/devices/Sonoff-POW-R1/index.md

The name for the device wasn't properly cased and thus gets sorted incorrectly any device list page that it's contained on.
Also, included an update to the alt-text for the image.

Update the name for the Sonoff POWR1

---

src/docs/devices/Shelly-Plus-2PM/index.md

The shelly plus 2pm shows it is only compatible with EU standard. However it has the same formfactor as the Shelly 1 and Shelly 1PM  
https://www.shelly.cloud/en/products/shop/shelly-plus-2-pm

Add us/uk support to Shelly Plus 2PM

---

src/docs/devices/Sonoff-POW-Elite-20a/index.md

Removed baud rate on logger as several users report non-functioning cse7766 when set https://community.home-assistant.io/t/sonoff-pow-elite-configuration/472671/27?u=bigwoof

Remove logger baud rate on Sonoff Pow Elite 

---

src/docs/devices/Wyze-Outdoor-Plug/index.md

Adds binary daylight sensor
Adds notes about the lux sensor and bluetooth proxy

Wyze-outdoor-plux Lux Sensor

---

src/docs/devices/Shelly-Plus-Plug-S/index.md

Trying to use this config with `esphome` 2023.9.3 gives this error:
```text
The restore_state option has been removed in 2023.7.0. Use the restore_mode option instead.
```

Remove `restore_state` from Shelly Plus Plug S config

---

src/docs/devices/Beca-Thermostat/index.md

As a tiny follow up on PR #529, merged last week (thanks!), I went ahead and bought a BHT-002-GCLW**DB**, featuring "WiFi dual-band support". This is accomplished by utilizing a Tuya WBR3D, which is based on the Realtek RTL8720DN. LibreTiny does not yet support this chip -- https://github.com/libretiny-eu/libretiny/issues/44 has some relevant context.
Add a note to the documentation, so that users are aware and hopefully avoid these variants.

Beca thermostat: add note about the RTL8720xx variants

---

src/docs/devices/Brilliant-Smart-Plug/index.md

Changed led output pin from GPIO13 to GPIO12 because GPIO 13 didn't do anything on my devices but GPIO12 does.
Update url at the top to the currently correct one (2023-10-22) Added device model number
Used substitutions for device name and !secret for more parameters.
Changed status "red_led" functionality to match original firmware behaviour. LED behaviour should be:
- Blinking red when initializing or not ok
- Solid red when connected, status ok and relay off
- Solid blue when relay on and status ok
Added basic comments about what sections and lines are doing for noobs like me to understand.

Update status led gpio, function and some comments

---

src/docs/devices/Sonoff-POWR316-16a/index.md

Changes:
- this model has no display so pin GPIO14 (TM1621 DA) is not used
- GPIO16 is "CSE7766 Rx" pin, status led is set up on pin GPIO05 in other part of basic configuration

Fix Sonoff POW Origin 16Amp (POWR316) description

---

src/docs/devices/Shelly-Plus-1-Mini/index.md

I've recently, flashed ESPHome firmware to my shelly plus 1 mini device and tested same temperature sensor configuration example that provided on https://devices.esphome.io/devices/Shelly-Plus-1PM-Mini and it works.

Shelly Plus 1 Mini documentation update

---

src/docs/devices/Shelly-Plus-PM-Mini/index.md

I just got my hands on the new Shelly Plus PM Mini. It is indeed just a "stripped down" Shelly Plus 1PM Mini. 
Chip, Temperature Sensor and Power Sensor seem to be identical. I flashed it via UART, the pinout is identical too.

New Device: Shelly Plus PM Mini

---

src/docs/devices/Globe-Electric-Wi-Fi-Smart-Plug-50329/index.md

Device is supported by latest versions of esphome, fork is not needed anymore.

Update Globe 50329

---

src/docs/devices/Wyze-Outdoor-Plug/index.md

INPUT_PULLDOWN set to `inverted: True` in the examples makes restore_mode set relay state randomly on power up

Wyze outdoor plug: restore_mode inoperable with pulldown inverted

---

src/docs/devices/Wyze-Plug-2021/index.md

The Wyze Plug nominally under the WLPP1 model seems to have different variants. One purchased currently in late 2023 appears to be a WLPP1CFH model number, uses a ESP32-C3 variant microcontroller, and different GPIOs.
Not sure what the community's preference is for how we want to document this, but I made a stab at it.

Update wyze plug gpios

---

src/docs/devices/Etekcity-ESO15-TB-Smart-Outdoor-WiFi-Outlet-Plug/index.md

Stock hlw8012 values assume different resistor values than is used on this board.  Stock will show a voltage around 20% higher than actual (stock value is 2350).  This just makes the current sensing values junk.  I've tested the new values with a KillaWatt meter.

Modify Etekcity Outdoor WiFi Outlet ESO15-TB yaml for proper voltage display

---

src/docs/devices/Sinilink-XY-WFUSB-USB-Switch-Relay/index.md

Just a small correction. It says the pins used for programming are 1mm but they are actually 1/20" or 1.27mm

Sinilink XY-WFUSB  programming pin pitch correction (1.27mm)

---

src/docs/devices/Sonoff-Mini-Relay/index.md

The Sonoff Mini docs specify using pin 13 in two places. In [ESPHome 2022.12 reusing a pin results in an error](https://esphome.io/changelog/2023.12.0.html#pin-reuse-validation). This fixes the config for the Sonoff Mini to ignore this error. I'm honestly not sure if there is a better way to handle this.

Update Sonoff Mini Relay Docs to use "allow_other_uses" for ping 13

---

src/docs/devices/AirGradient-One/index.md

Was previously getting:
```
INFO ESPHome 2023.12.5
INFO Reading configuration /config/esphome/airgradient.yaml...
ERROR Error while reading config: Invalid YAML syntax:
while parsing a block mapping
in "<unicode string>", line 345, column 3
did not find expected key
in "<unicode string>", line 347, column 3
```
Tested this change and things successfully validates now. Not sure if the lights are working as intended, but the sensors are reporting and the display itself looks good.
cc @lilmansplace who added initial support for AirGradient-One in #608

Fix invalid AirGradient-One yaml

---

src/docs/devices/Shelly-EM/index.md

The new ADE7953 I2C component is improved and provides the required sensors natively, which are now used here. I removed the totals, because they don't make sense like in a Shelly 3EM.

Use of the new ADE7953 I2C component

---

src/docs/devices/Shelly-Plus-2PM/index.md

The ade7953 sensor component has been renamed to ade7953_i2c.

chore: update ade7953 to ade7953_i2c for shelly plus 2PM device

---

src/docs/devices/Shelly-Plus-1-Mini/index.md

The board type contains v1 at the end, while only the 1 is a valid part.

Documentation: fix board type for Shelly-Plus-1-mini

---

src/docs/devices/Sonoff-S31/index.md

Updates from CSE7766 cause flooding, adding filter throttles to make it update every 60s (sanely).

S31 - Changes for CSE7766 in 2024.2.0

---

src/docs/devices/ESP32-Deep-Sleep-BME280/index.md

ESP32-Deep-Sleep using only **global variables** and MQTT, without Home Assistant automation

ESP32-Deep-Sleep without Home Assistant automation

---

src/docs/devices/ESP-12F-Relay-X4/index.md

From my own experiences with this board as well as the "more detailed manual" and this guide here: https://templates.blakadder.com/ESP12F_Relay_X4.html
GPIO16 is used for RXD on this board so it will always be briefly powered on at boot. This may be an issue for someone's use case so it should be addressed in documentation. I have found the suggested use of GPIO15 on the tasmota html page to allow relay1 to function normally.

Update ESP-12F_Relay_X4 documentation to address issues with GPIO16 & relay1

---

src/docs/devices/Sonoff-THR320D/index.md

Hi all,
I've found an error in the code for the Sonoff THR320D that is causing the device to become very hot.
The relays GPIOs were considered as active-low (`inverted: True`), but they are actually active-high.
This was probably making the bistable main relay coil to overheat or the drivers to short circuit or something like that, making the whole device too hot to touch.
After the fix, the device doesn't get hot at all, so I'm sure that was the issue.
You can check here that relays GPIOs are actually active-high: https://templates.blakadder.com/sonoff_THR320D.html 
I think this should be fixed as soon as possible, because the device was getting so hot that it could be a fire hazard!

Remove `inverted` from Sonoff THR320D relays GPIOs

---

src/docs/devices/Sonoff-S31/index.md

It is my understanding that since energy is a increasing unit over time, it should not be averaged for accuracy. It will accumulate measurements until the throttle window has expired. I’m also referring to the example of the sensor : https://esphome.io/components/sensor/cse7766

Change energy throttle CSE7766.

---

src/@rocketseat/gatsby-theme-docs/components/Sidebar/index.js
src/components/DeviceLink.js
src/components/MadeForESPHomeDevices/madeforesphomedevices.js
src/config/sidebar.yml
src/docs/made-for-esphome.mdx

This adds a generated page with all devices that have `made-for-esphome: True` set in their source. 
Devices adding this flag set to true should be verified with the ESPHome team before merging to ensure only approved devices show in the list.

Add made for esphome list page

---

src/docs/devices/ESP32-Relay-X1/index.md

Add a link to a 3D printable enclosure design for the Relay X1 board.

[Relay X1] Add link to enclosure design

---

src/docs/devices/Sonoff-BASIC-R4-v1.0/index.md

`esp32dev` is not the correct board type. `esp32-c3-devkitm-1` is the correct board type.
Please reference [ESPHome Issues #5757](https://github.com/esphome/issues/issues/5757)

Correct board type for Sonoff Basic R4

---

src/docs/devices/DETA-Grid-Connect-Single-Gang-Two-Way-6951HA/index.md

Added documentation for previously undocumented on ESPHome Devices for Deta GridConnect Single Gang Two-Way Switch 6951HA

Added Deta GridConnect Single Gang Two-Way Switch 6951HA

---

src/docs/devices/Shelly-25/index.md

Per the documentation of https://esphome.io/components/sensor/ade7953.html the sensor "ade7953_i2c" has been renamed to "ade7953_i2c".

Changed ade7953 to ade7953_i2c

---

src/docs/devices/M5Stack-M5StickC-PLUS/index.md

There is a timing issue for the using the grove/HY2.0-4P connector as  i2c bus, the axp192 must be running before.

setup_priority-after-axp192

---

src/docs/devices/TreatLife-DS02F/index.md

Recently dealt with some DS02F and wanted to suggest an update to use the new wb3s board and cloudcutter method for flashing.  I have also updated the configuration example to include a switch to control Treatlife's "Light Mode".

Update Treatlife DS02F to reference wb3s board and cloudcutter

---

src/docs/devices/Renke-RS-FXJT-N01-Wind-Direction/index.md

In addition to using the Windows tool, you can change device's modbus addresses directly.

Wind direction meter - change address from ESPHome

---

src/docs/devices/Renke-RS-FSJT-N01-Wind-Speed/index.md

In addition to using the Windows tool, you can change device's modbus addresses directly.

Wind speed meter - change address from ESPHome

---

src/docs/devices/Duux-Whisper-Flex-Smart-Fan-DXCF10/index.md

Hide the selects for oscillation from Home Assistant and create template switches instead. This makes it easier to use the oscillation with toggle buttons in Home Assistant.

Expose switches instead of selects for oscillation of Duux Whisper-Flex-Smart-Fan

---

src/config/sidebar.yml

These are not boards. These are microcontroller types on a plethora of various board types.

MCU instead of board

---

src/docs/devices/Shelly-PM-Mini-Gen3/index.md

Boot loop occurs unless flash_mode: dio is enabled.
This PR adds this to the example yaml.

Update Shelly PM Mini Gen3

---

src/docs/devices/Inkbird-PTH-9CW/index.md

A Tuya device, sold as either PTH-9CW or INK-CO2W.
`https://inkbird.com/products/wi-fi-co2-detector-ink-co2w`
`https://www.amazon.com/dp/B09YV4FQD2`

Add Inkbird PTH-9CW/INK-CO2W CO2 sensor

---

src/docs/devices/M5Stack-Dial/index.md

M5Stack Dial has a pcf8563 time source. Added it along with a read `on_boot` and a write `on_time_sync` from homeassistant. You could sub out the homeassistant time source for sntp but I have not tested this.

Add RTC to M5Stack-dial

---

src/docs/devices/Shelly-3EM/index.md

Add information about proper connection in case only subset of clamps is used in order to avoid bad readings.

Update shelly 3em page with troubleshoting information

---

src/docs/devices/Shelly-1PM-Mini-Gen3/index.md

Relay GPIO 7 is TX, GPIO5 is the relay.

Fix wrong relay GPIO for Shelly 1PM Mini Gen3

---

src/docs/devices/Nous-A1t/index.md

ESPhome now requires a platform to be specified for OTA. Added

Update index.md - add platform to OTA

---

src/docs/devices/Apollo-Automation-PLT-1/index.md

Fixed Broken Apollo PLT-1 GitHub Link

Fix Broken Apollo PLT-1 GitHub Link

---

src/docs/devices/Sonoff-POW-R2/index.md

- Use status_led light component for the blue LED

Sonoff Pow R2: Update and use status_led light component

---

src/docs/devices/Sonoff-BASIC-R2-v1.4/index.md
src/docs/devices/Sonoff-POW-R2/index.md

The links to the status_led light component were using relative paths, but they are hosted on esphome.io, not devices.esphome.io. This PR fixes to use absolute links.

Fix links to status_led light component

---

src/docs/devices/SONOFF-POWCT/index.md
src/docs/devices/Sonoff-4CH-Pro-R2/index.md
src/docs/devices/Sonoff-BASIC-R2-v1.4/index.md
src/docs/devices/Sonoff-BASIC-R4-v1.0/index.md
src/docs/devices/Sonoff-POWR316-16a/index.md

All these Sonoff relays require disassembly, but soldering optional (you can simply place dupont into the pins slots and hold them at an angle rather than solder the pin headers).

Add difficulty level 3 (disassembly required) for Sonoff relays

---

src/docs/devices/Sonoff-S31/index.md

Address breaking change from esphome update ESPHome 2024.10.0 - 16th October 2024: https://github.com/esphome/esphome/pull/7549

Sonoff S31 parity even change

---

src/docs/devices/Sonoff-S31/index.md

CSE7766 requires even parity since https://github.com/esphome/esphome/pull/7549. This PR fixes the recipe for the Sonoff-S31, which uses the CSE7766.

Fix Sonoff-S31

---

src/docs/devices/Tinxy-4N-Fan-Regulator/index.md

Necessary Baud Rate changes for Tinxy 4N for successful flashing because flashing fails with esphome web flasher.

Necessary Baud Rate changes for Tinxy 4N for successful flashing

---

src/docs/devices/ESP-12F-Relay-X8/index.md

added status LED (GPIO2)
corrected typo (8 relays, not 4)

added status LED for device ESP-12F_Relay_X8

---

src/docs/devices/M5Stack-Dial/index.md

The M5Stack Dial has a second i2c bus available via a grove connector port, labeled "Port A" on the rear of the device. This change adds support for the second i2c bus per the [documentation](https://docs.m5stack.com/en/core/M5Dial) on the M5Stack site.

Add i2c to M5Stack-Dial

---

src/docs/devices/Ghome-SW5/index.md

Added instructions for OTA flashing of GHome SW5 using Tuya-cloudcutter
Added instructions to use Tuya Cloudcutter to OTA flash the switch
- [ X ] Update existing device
- [ X ] There are no passwords or secrets references in any examples. 
- [ X ] The `wifi` or `ethernet` block has no static / manual ip address specified.
- [ X ] The first configuration provided should be **hardware definitions only**.

Update SW5 instructions to include tuya-cloudcutter

---

src/docs/devices/Sonoff-M5/index.md

The Matter compatible version of the Sonoff M5 light switch series can't be flashed, they have a locked bootloader. This PR adds a note in the device's page. 
This is verified by me and **[others](https://community.home-assistant.io/t/flashing-sonoff-switchman-m5-white-matter-version/741099/5)**.

Add note for Sonoff M5 Matter version that can't be flashed

---

src/docs/devices/Duux-Whisper-Flex-Smart-Fan-DXCF10/index.md

Switching the horizontal oscillation to oscillation_datapoint for Tuya fan. Gets rid of a button and lamba calls. Would be great if Tuya fan also had a vertical oscillation like Tuya climate 😄

Switch to oscillation_datapoint for Tuya fan

---

src/docs/devices/Guition-ESP32-S3-4848S040/index.md

This adds additional relay outputs for the "Three way relay" version of the Guition ESP32-S3-4848S040

Add 3-relay config for Guition-ESP32-S3-4848S040

---

src/docs/devices/Feit-PLUG3-WIFI-WP-2-N/index.md

There was an extra invalid line in the switch config.

remove invalid line in config

---

src/docs/devices/Arlec-PC191HA-Plug/index.md

It appears that Series 2 devices are a mixed bag of internals - added some information to help clarify which wifi module is actually inside a series 2 plug without the need to open it. 
There is some discussion about the multiple modules here: https://community.home-assistant.io/t/kickstart-bk7231t-to-esphome-add-on/701658

Update Arlec PC191HA to include information about multiple modules

---

src/docs/devices/Sinilink-XY-WPCE/index.md

Sinilink XY-WPCE brings output high on reboot / loss of wifi triggering inadvertent action on connected PC. Setting it to off on boot fixes this behaviour.

Docs example updated for Sinilink XY-WPCE

---

src/docs/devices/Sonoff-POWR316-16a/index.md

- Fixed WiFi LED behaviour
- Add required `parity: EVEN` on `uart`.
- Remove unsupported `update_interval: 10s` on `platform: cse7766`.
- Removed references to undefined substitution `dev_nice_name`.
- Setup standard power LED illuminates when relay in turned on behaviour.
- Added internal temp, WiFi signal and IP reporting.

Fix errors. Improve LED behaviour : Sonoff POW Origin 16Amp (POWR316)

---

src/docs/devices/LSC-Battletron-Desk-Strip-3-meter-3206528/index.md

Fix lsc battletron 3206528

---

src/docs/devices/Tomzn-TOB9-VAP/index.md

Migrate TomZN TOB9-VAP to use H-Bridge component, and also update LEDs configuration based on [this](https://github.com/libretiny-eu/upk2esphome/issues/17#issuecomment-2551485979).

Migrate TomZN TOB9-VAP to use H-Bridge component

---

src/docs/devices/M5Stack-AirQ/index.md

moved some variables to substitutions, and fixed a bug with a sensor not consistently working, with a few other small tweaks due to changes in glyph validation.
- [ X] Update existing device
- [ X] There are no passwords or secrets references in any examples. 
- [ X] The `wifi` or `ethernet` block has no static / manual ip address specified.
- [ X] The first configuration provided should be **hardware definitions only**.

Fixed and improved AirQ YAML

---

src/docs/devices/Ghome-SW5/index.md

Added warning indicating that newly purchased GHome SW5 smart switches may contain a Lightning Semi LN882H.

Update GHome SW5 index.md to warn users about new model using LN882H

---

src/docs/devices/Xiaomi-Mijia-Bedside-Lamp-2/index.md

The linked repository https://github.com/mmakaay/esphome-xiaomi_bslamp2 no longer has a "main" branch; links changed to refer to the "dev" branch", preferring this over one of the "release/" branches. OK?

Fixing broken links in Xiaomi-Mijia-Bedside-Lamp-2/index.md

---

src/docs/devices/BudapestMetroDisplay/index.md

Add the configuration for the BudapestMetroDisplay display.

Add BudapestMetroDisplay

---

src/docs/devices/Tongou-TO-Q-SYS-JWT-power-meter/index.md

An M2.5 screw seems like a better fit than M3.
Also make the algorithm easier to read.
Adjust the text on device reassembly.

Rewrite the reassembly text for TO-Q-SYS-JWT & use a new Libretiny-native UART buffer size option

---

src/docs/devices/ESP32E-Relay-X8/index.md

ESP32E-Relay-X8: Copy relay GPIOs to pin listing.

---

src/docs/devices/Shelly-Plus-Plug-S/index.md

See https://github.com/esphome/esphome/pull/7770#issuecomment-2555924247

Remove rmt_channel as it was removed from IDF

---

src/docs/devices/Mi-Desklamp-1S/index.md
src/docs/devices/Mi-Desklamp-Pro/index.md

As per https://github.com/esphome/issues/issues/6333, since esphome 2024.10 the `ignore_efuse_mac_crc` flag is not enough - this PR adds the missing `ignore_efuse_custom_mac` to the affected devices.
I also took the liberty to update the component usage in provided example configs to their up-to-date recommended structures (e.g. `ota` as a list); Additionally I've re-enabled `web_server` and `captive_portal`, previously unavailable in esp-idf.
I've verified the updated config on a 1S model; Pro is virtually identical, at least pinout-wise.
If preferred, I can split out the changes into a minimal efuse flag fix and a separate commit/PR for the rest.
A more involved example can be provided in a separate configuration …

Mi/Xiaomi Desklamps: fix ignore_efuse_custom_mac, update component usage

---

src/docs/devices/Sonoff-POW-Elite-16a/index.md
src/docs/devices/Sonoff-POW-Elite-20a/index.md

Fixed sample YAML for a couple of Sonoff devices, to match current ESPHome

Fixed sample YAML for a couple of Sonoff devices, to match current ESPHome

---

src/docs/devices/Sonoff-S31/index.md

* Moves platform configuration to the new-style `esp8266` section (from `esphome`)
* Disables `early_pin_init`
* https://esphome.io/components/esp8266.html recommends disabling this on switches to avoid flickering during updates
* Fixes OTA config when used with modern ESPHome versions
* Fixes typo in comment

Updates to the Sonoff S31 basic config

---

src/docs/devices/Sonoff-S31/index.md

Replaced potentially problematic _restore_mode_ of _ALWAYS_ON_ with _ALWAYS_OFF_. 
Relay Coils are inductive loads and it can be reasonably assumed not all UART adapters will handle the inrush and back EMF appropriately. Changing _restore_mode_ to _ALWAYS_OFF_- avoids an implicit endorsement of a dangerous (to equipment) action when using the example code to do the initial flash. It also maintains the presentation that an option to have relay on by default exists. 

Sonoff S31 - Powering Relay Coil in Example May Damage UART Adapters

---

src/docs/devices/Sonoff-M5/index.md

Added the 'platform: esphome' to the ota sections of the examples for the Sonoff M5 Switches.

Updated examples with ota platform fixes

---

src/docs/devices/eWeLink-SANT-SUD01/index.md

This change resolves this fatal error when compiling the basic config:
`Either optimistic mode must be enabled, or turn_on_action or turn_off_action must be set, to handle the switch being set.`

update eWeLink-SANT-SUD01 basic config

---

README.md

The "upstream" JonathanAdams repo has been archived since 2020. It feels weird to self-identify as a fork, now that the project has been officially sanctioned by the ESPHome mothership.
Change "this is a fork" message to reflect official adoption.

README: update "this is a fork" disclaimer.

---

src/docs/devices/AHRise-AHR-083/index.md
src/docs/devices/AVATTO-S06-IR-Remote-no-temp-no-humidity/index.md
src/docs/devices/AWP02L2/index.md
src/docs/devices/AWP04L/index.md
src/docs/devices/Acenx-SOP04-US/index.md
src/docs/devices/AirGradient-DIY/index.md
src/docs/devices/Aoycocr-X10S-Plug/index.md
src/docs/devices/Aoycocr-X13-Outdoor-Plug-2AKBP-X13/index.md
src/docs/devices/Arlec-10m-Smart-Extension-Lead-Plug-AEL10HA/index.md
src/docs/devices/Arlec-6000HA-Switch/index.md
src/docs/devices/Arlec-FL052HA-Security-Flood-Light/index.md
src/docs/devices/Arlec-Grid-Connect-Smart-9W-CCT-LED-Downlight/index.md
src/docs/devices/Arlec-Grid-Connect-Smart-9W-RGB-CCT-LED-Downlight/index.md
src/docs/devices/Arlec-Grid-Connect-Smart-LED-Globe-CWWW/index.md
src/docs/devices/Arlec-Grid-Connect-Smart-LED-RGBWW-10W-GLD322HA/index.md
src/docs/devices/Arlec-PB89HA-Plug/index.md
src/docs/devices/Arlec-PC189HA-Plug/index.md
src/docs/devices/Arlec-PC288HA-Plug/index.md
src/docs/devices/Arlec-Smart-5m-LED-Strip-Light/index.md
src/docs/devices/Athom-BR30-Bulb/index.md
src/docs/devices/Athom-E27-15W-Bulb/index.md
src/docs/devices/Athom-E27-7W-Bulb/index.md
src/docs/devices/Athom-GU10-Bulb/index.md
src/docs/devices/Athom-Smart-Plug-AU/index.md
src/docs/devices/Athom-Smart-Plug-TP29/index.md
src/docs/devices/Aukey-SH-PA1-Smart-Plug/index.md
src/docs/devices/Awow-EU3S-Power-Monitoring-Plug/index.md
src/docs/devices/Azpen-Home-With-USB/index.md
src/docs/devices/anoopsyche-jh-g01b1/index.md

Updates examples to remove old style `esphome` block configurations

[A] Remove old style configs

---

src/docs/devices/geiger-counter/index.md

Add advanced version of config, which update sensor values once per second and calc dose value depending on historical data during last minute

Add advanced version of config for devices/geiger-counter

---

src/docs/devices/SiloCityLabs-Dikale-Filament-Dryer/index.md

Initial commit for device creation of SiloCityLabs Filament Dryer PCB.

Added SiloCityLabs dikale filament dryer pcb

---

src/docs/devices/Sonoff-Mini-Relay/index.md

Replace old style platform configuration
Related: https://github.com/esphome/esphome/pull/8118

Replace old style platform configuration

---

src/docs/devices/Shelly-1PM-Gen3/index.md

I added basic and application-specific usage of the Shelly 1PM Gen3 relay and power metering device.  This is a separate device from the Shelly 1PM Mini Gen3.  The 1PM Mini Gen3 only has an 8A relay while the 1PM Gen has a 16A relay.

New device: Shelly 1PM Gen3

---

src/docs/devices/Guition-ESP32-S3-4848S040/index.md

[Change] updated Guition ESP32-S3-4848S040 480*480 Smart Screen to compile with esphome 2025.2.2 and native lvgl (no external components)
[New] added a screensaver when blanked,
[New] added a clock display
[New] added an ip address label

updated Guition ESP32-S3-4848S040 480*480 to esphome 2025.2.2

---

src/docs/devices/SiloCityLabs-Airtap-t-series-3btn/index.md

Initial commit for device creation of SiloCityLabs Airtap T4 3 button pcb.

Added SiloCityLabs 3 button airtap pcb

---

src/docs/devices/Athom-Energy-Meter-EM2/index.md
src/docs/devices/Athom-Energy-Meter-EM6/index.md
src/docs/devices/Athom-Mini-Relay-RS01C3/index.md
src/docs/devices/Athom-Smart-Plug-PG01V3-EU16A/index.md
src/docs/devices/Athom-Smart-Plug-PG03V3-US16A/index.md
src/docs/devices/Athom-Smart-Plug-PG04V3-UK16A/index.md
src/docs/devices/Athom-Smart-Plug-PG05V3-AU10A/index.md

Several pages contained "eps32-c3", instead of "esp32-c3".

Correct typo eps32-c3 > esp32-c3

---

src/docs/devices/DETA-Grid-Connect-Single-Gang-Two-Way-6951HA/index.md
src/docs/devices/DETA-Grid-Connect-Two-Gang-Two-Way-6952HA/index.md

Update configuration examples for DETA 6951HA and 6952HA based on optimisations I've made in my own Home Assistant setup.
This config exposes a "light" entity instead of a "switch" entity, eliminating the overhead of converting it in Home Assistant.

Simplify DETA 6951ha and 6952ha config and expose as Light components

---

src/docs/devices/MJ-SJ01/index.md

Adds a link to and brief explanation of my new configuration for the MJ-SD01 switch. Hopefully this format is acceptable, since the README there is a lot more extensive than seems appropriate for an esphome-devices page, and I wanted to keep this reference relatively brief. It is added as a new section above the existing section.

Add section on packaged MJ-SD01 config

---

src/docs/devices/Tuya-Generic-IRC03-IR-Blaster/index.md
src/docs/devices/Tuya-Generic-WiFi-IR-Remote-Control/index.md

Adds a disclaimer to the Tuya IRC03 and Tuya Generic IR Blaster pages warning that despite looking outwardly identical, the devices have different internals and accordingly different pinouts. Updates the IRC03 page with additional flashing information. Adds a little usage information to the IRC03 page regarding use with the Home Assistant integration SmartIR.

Update Tuya IRC03 IR Blaster and Tuya Generic IR Blaster pages

---

src/docs/devices/lanbon_l8/index.md

With 2025.5.0, the example Lanbon-L8 configuration was generating an error because 'octal' mode is not supported for PSRAM on the ESP32.
New with 2025.5.0 is the mipi_spi platform with a built-in model for the Lanbon-L8 which greatly simplifies the configuration

Update Lanbon L8 configuration for 2025.5.0

---

src/docs/devices/Sonoff-POW-R2/index.md

The [currently available code listing](https://devices.esphome.io/devices/Sonoff-POW-R2#basic-configuration) fails with compilation (in esphome v2025.4.0) errors due to invalid characters in name, missing platform for OTA and missing explicit parity setting for UART.
I assume all errors are caused by some breaking changes that piled up in esphome while this listing was not updated.
Example compilation error caused by invalid characters in name:
```
esphome compile powr2-example.yaml
INFO ESPHome 2025.4.0
INFO Reading configuration powr2-example.yaml...
Failed config
esphome: [source powr2-example.yaml:6]
'S' is an invalid character for names. Valid characters are: abcdefghijklmnopqrstuvwxyz0123456789-_ (lowercase, no spaces).
name: Sonoff POW R2
project:
name: Sonoff.relay
version: POWR2 …
```

Updated basic configuration for Sonoff POW R2

---

src/docs/devices/M5Stack-M5StickC-PLUS/index.md
src/docs/devices/M5Stack-M5StickC-PLUS2/index.md

Fix compilation for M5StickC-Plus
Note: compiles successfully, but untested due to lack of hardware
(therefore I didn't migrate the display to `ili9xxx`).

Fix compilation for M5StickC-Plus

---

src/docs/devices/ESP-12F-Relay-X8/index.md

- Split the intertwined GPIO info into header and pinout sections.
- Notate which relays will be on during boot.
- Add link to an ESP-12F datasheet.
- Clarify how to power the board for flashing.

Update ESP-12F_Relay_X8 GPIO header

---

src/docs/devices/MagicHome-ZJ-WFMN-A-RGBW/index.md

- Removed duplicated config (basic config + extends config). They both were nearly the same except that they got out of sync. I kept only the extends config
- Updated deprecated options in MagicHome template
- Removed user-specific config (static IPs, disabled logging etc)
- Adds more effects and their IR codes

MagicHome-ZJ-WFMN-A-RGBW: Removing deprecated options and adding IR codes 

---

src/docs/devices/Kogan-Smarterhome-Smart-Power-Board-With-Usb-Ports-Energy-Meter/index.md

* use `light: platform: status_led` (which was implemented after this template was first written)
* allow selection of relay to toggle with multi_click
* no longer listed for sale, point to manual instead
I'm not sure if relay selection adheres to the last checklist item, but this restores functionality.
- [?] The first configuration provided should be **hardware definitions only**.

KASPS10A3P3UA - use `platform: status_led`; allow outlet selection with multi_click

---

src/docs/devices/UltraPro-WFD4001-Light-Switch/index.md

Add difficult and pin 6 description to UltraPro WFD4001.

Add difficulty and pin 6 to UltraPro WFD4001.

---

src/docs/devices/KinCony-KC868-AIO/index.md

Changed the clk_mode in the basic configuration in favour of clk

Deprecated clk_mode replaced with clk

---

src/docs/devices/DETA-Grid-Connect-Outdoor-Smart-Plug-6294HA-Series-2/index.md

Added support for DETA-Grid-Connect-Outdoor-Smart-Plug-6294HA-Series-2

Added support for DETA-Grid-Connect-Outdoor-Smart-Plug-6294HA-Series-2

---

src/docs/devices/LSPS5-Tuya-1-2-3-Gang-Switch/index.md

Fix for OTA Platform for ESPHome 2025.7+
```
INFO Generating C++ source...
Traceback (most recent call last):
File "/usr/local/bin/esphome", line 10, in <module>
sys.exit(main())
^^^^^^
File "/esphome/esphome/__main__.py", line 1087, in main
return run_esphome(sys.argv)
^^^^^^^^^^^^^^^^^^^^^
File "/esphome/esphome/__main__.py", line 1074, in run_esphome
rc = POST_CONFIG_ACTIONS[args.command](args, config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/esphome/esphome/__main__.py", line 512, in command_run
exit_code = write_cpp(config)
^^^^^^^^^^^^^^^^^
File "/esphome/esphome/__main__.py", line 212, in write_cpp
generate_cpp_contents(config)
File "/esphome/esphome/__main__.py", line 219, in generate_cpp_contents
for name, component, conf in iter_component_configs(CORE.config): …
```

Fix for OTA Platform for ESPHome 2025.7+
