esphome/esphome-devices

- _devices/Sonoff-4CH-Pro-R2/Sonoff-4CH-Pro-R2.md
From @zewelor at https://github.com/jonathanadams/esphome-configs/pull/160
> Fix link
> Retarget PR: "Update Sonoff-4CH-Pro-R2.md"

- _devices/Gosund-SP112/Gosund-SP112.md
Wanted to share my template for the Gosund SP112 as it's a bit special having the physical button attached to the analog input pin.
> New device: Gosund SP112

- adding-devices.md
For newbies, I think the workflow by using the Github buttons is easier than manually fork and branch creation.
> Documentation: Description of easier fork and branch creation and and some missing letters

- _devices/Generic-Remote-Receiver/Generic-Remote-Receiver.md
> Adding a generic IR code receiver

- _devices/Gosund-SP112/Gosund-SP112.md
Sentence structure edit on first line
& 'videl' >> video
> Small spelling changes

- _devices/DETA-Grid-Connect-Smart-Double-Touch-Power-Point/DETA-Grid-Connect-Smart-Double-Touch-Power-Point.md
> Create  DETA-Grid-Connect-Smart-Double-Touch-Power-Point.md

- _devices/Novostella-20W/Novostella-20W.md
via @setola, testing a new branch+commit
> Add color_interlock option for Novostella Flood 20w

- _devices/Gosund-WP3/Gosund-WP3.md
#32 
Made updates to the config for the Gosund WP3 based on testing with my devices.
> Alternate config for Gosund WP3

- _devices/Shelly-25/Shelly-25.md
Source: https://savjee.be/2020/11/shelly25-esphome-potential-fire-hazard-fix/
> Fix for overheating with ESPHome

- _devices/LSC-Smart-Connect-Switch/LSC-Smart-Connect-Switch.md
Found out that devices sold at Action stores are not compatible anymore
> LSC Smart Plug: Add warning that new devices are incompatible

- _devices/Feit-BPDIM-WIFI-2/Feit-BPDIM-WIFI-2.md
I have followed the linked guide and it does, indeed, work as desired. With Tuya-convert no longer an option, it is a comfort to know that these are serial flash capable, if you have the right tools and determination.
> Add link to "how to serial flash" guide

- _devices/BlitzWolf-BW-SHP6/BlitzWolf-BW-SHP6.md
- _devices/BlitzWolf-BW-SHP7/BlitzWolf-BW-SHP7.md
More info: https://github.com/esphome/esphome/pull/1198
> BW SHP 6/7: introduce new HLW8012 energy sensor

- _devices/Sonoff-Mini-Relay/Sonoff-Mini-Relay.md
> Updated board to esp8285

- _devices/Gosund-WP6/Gosund-WP6.md
> Added config for Gosund WP-6

- _devices/DETA-Grid-Connect-Smart-Double-Touch-Power-Point/DETA-Grid-Connect-Smart-Double-Touch-Power-Point.md
This PR includes some fixes I needed to make to the basic configuration to get it to compile, and expose both switches to Home Assistant.
I've also added some basic information on flashing, including basic disassembly directions for serial flashing.
> update basic config + add flashing info for the Deta Grid Connect Smart Double Touch Power Point

- src/docs/devices/BlitzWolf-BW-SHP7/index.md
Added fix for sporadic SHP7 reboots
More information: 
https://community.home-assistant.io/t/working-config-for-blitzwolf-bw-shp7/216513/16?u=dawidcie
> Added fix for sporadic SHP7 reboots

- src/docs/devices/Shelly-1/index.md
A toggle switch behaves differently than a push-button switch; it has no possibility to perform a double click or long click.
> Add configuration example for a toggle switch

- src/docs/devices/Gosund-UP111/index.md
> Update Amazon link for Gosund UP111

- src/docs/devices/Shelly-1PM/index.md
Add example configuration for Shelly 1PM
> Add Shelly-1PM

- src/docs/devices/Gosund-SP111/index.md
> Fixed type for SP111 to plug

- src/docs/devices/Orno-Single-Phase-Energy-meter-OR-WE-514/index.md
> New device Orno-Single-Phase-Energy-meter-OR-WE-514

- src/docs/devices/Deta-Grid-Connect-Smart-Fan-Speed-Controller-with-Touch-Light-Switch/index.md
See: https://github.com/esphome/issues/issues/2675
> Fixed pin 16 error

- src/docs/devices/Treatlife-Wall-Switch/index.md
* Fix  group.all_lights -> light.all_lights
* Add missing 'target:' to service.
> Fix sample automation

- src/docs/devices/Vivitar-HA-1007-AU-Power-Strip/index.md
Based on https://github.com/jonathanadams/esphome-configs/pull/137 
Resolves https://github.com/esphome-devices/esphome-devices/issues/146
> Add Vivitar HA-1007-AU Power Strip

- src/docs/devices/Gosund-SP1/index.md
> Add Gosund SP1 Device

- src/docs/devices/Treatlife-Wall-Switch/index.md
Update the treatlife 2way switch template.
> Fix template that uses binary sensor on output pin

- src/docs/devices/Sonoff-S31/index.md
Hope this helps the next buyer be prepared :)
> Add note on how to do initial install for Sonoff S31

- src/docs/devices/MJ-S01/index.md
Martin Jerry Wall Switch MJ-S01 example configuration
> Martin Jerry Wall Switch MJ-S01

- src/docs/devices/Kogan-Smart-Air-Purifier-2S/index.md
I initially provided incorrect uart pins. These should now be correct.
Sorry if my workflow is a mess, I'm really new to contributing on GitHub and got confused at a few points. Will try to do some more self-education before next contributions.
> Corrected UART pins

- src/docs/devices/Shelly-Pro-1/index.md
i've added all my research to this file and hope it will help some other people working with this device.
> Shelly Pro 1 Pinout

- src/docs/devices/Sonoff-S31/index.md
Allows the total daily energy to be pulled into HA Energy dashboard.
> Add total_daily_energy

- src/docs/devices/Shelly-25/index.md
Was receiving errors because power is by the watt, but energy should be the Wh or kWh.
> Updated Total Daily Energy to kWh

- src/docs/devices/Shelly-1/index.md
Replaced the word "Homa" with "Home".
> Fix minor spelling error

- src/docs/devices/Orno-Triple-Phase-Energy-meter-OR-WE-520/index.md
> ORNO OR-WE-520 (Triple-Phase Energy Meter)

- src/docs/devices/DETA-Grid-Connect-Smart-Dimmer-Switch/index.md
- src/docs/devices/DETA-Grid-Connect-Smart-Switch/index.md
Add configuration and conversion notes for Deta Dimmer Switch
> Deta Dimmer Switch

- src/docs/devices/Shelly-Plus-i4/index.md
> Update index.md Tidy up Generic Secrets

- src/docs/devices/MJ-SJ01/index.md
Incorrect syntax for lamda interval.
> Incorrect syntax for lamda interval.

- src/docs/devices/Globe-4-Inch-9W-Downlight-50359/index.md
Adding Globe 4" 9W Downlight (50359), based on https://templates.blakadder.com/globe_50359.html .
WT32C3-01N details pulled from https://templates.blakadder.com/WT32C3-01N.html .
> Add Globe 4" 9W Downlight (50359)

- src/docs/devices/Globe-4-Inch-9W-Downlight-50359/index.md
Few more changes... Kept the corrected date.
> Corrected EN pin information

- src/docs/devices/Mi-Desklamp-1S/index.md
Sorry for the delay. I updated the sources and fixed the compile Error. Hope it works for everyone.
> Fixed compile Error

- src/docs/devices/MJ-SJ01/index.md
Connect it as the status led.
Add more description to GPIO16.
> Add red led (GPIO4) to martin jerry dimmer MJ-SD01

- src/docs/devices/Mirabella-Genio-Smart-Universal-IR-Controller/index.md
I'm not able to use tuya-convert so programmed via serial.
> Add information for programming via serial loader

- src/docs/devices/Shelly-RGBW2/index.md
CWWW config. This repo helped me create it - hoping to return the favor
> Added Shelly RGBW2 CWWW config

- src/docs/devices/MJ-SJ01/index.md
- Green leds flashes on up/down button press when the brightness is already at the limit.
- Red led is on when the device is off, to make the switch more visible
- Do not use "interval" when used as a dimmer anymore. More CPU efficient.
- Number of incremental steps is now configurable.
- Lower the PWM frequency, which increases low intensity resolution.
- Improve button behavior to be more intuitive.
- Add a second example using the switch as a timed control. This is useful in a bathroom to have one switch for the lights, a second for the fan.
> MaUpdate MJ-SD01 with many featuresin

- src/docs/devices/Shelly-25/index.md
Use the math function "abs" for the inverted channel.
> Use a lambda and the math function abs

- src/docs/devices/Sonoff-POW-Elite-20a/index.md
- src/docs/devices/sonoff-pow-elite-20a/index.md
Add config example for Sonoff Pow Elite 20A (POWR320D) with all ESP sensors and bluetooth proxy.
This model has a bi stable relay.
> Sonoff Pow Elite 20A (POWR320D) doc

- src/docs/devices/Shelly-Plus-1PM/index.md
The existing example turns the switch into an odd three-way toggle.  Updated to look more like the Shelly 1 example.
> Updated Shelly Plus 1 PM example

- src/docs/devices/DETA-Grid-Connect-Smart-Switch/index.md
I was able to decouple the button led(s) from the relay output, so thaugh I would share here.
> Add suggested modification section

- src/docs/devices/ESP32E-Relay-X8/index.md
Initial file. I'll add the full pinout later, when I have time to review it.
> Initial ESP32 Realy Board x8 commit

- src/docs/devices/Nous-A5t/index.md
First try with Nous A5t, Everything working except small buttons
Correct GPIO link https://nous.technology/product/a5t.html
> Added Nous A5t

- src/docs/devices/Arlec-6000HA-Switch/index.md
See tasmota docs: https://templates.blakadder.com/deta_6000HA.html
Working for me :)
> Add arlec 6000ha

- src/docs/devices/Sonoff-THR320D/index.md
Relay works a little differently than originally suspected, see #341  
Also added switch for dry contact relay
> Fixes for THR320D main relay config

- src/docs/devices/Mi-Desklamp-Pro/index.md
- ESP-IDF 'recommended' version breaks the esp32 wifi stack during runtime. 4.4.1 works ok and builds successfully on aarch64/amd64.
- increase flicker frequency from 10kHz to 100kHz for brighter LED output.
- add ability to change flicker frequency on-the-fly.
- add 500ms power on/off transition to simulate original firmware behavior.
- debounce power button (5ms).
> Mi-Desklamp-Pro: fix runtime wifi error, custom flicker frequency

- src/docs/devices/Tuya-ZY-M100-Human-Presence-Sensor/index.md
text sensor not evaluating condition correctly added, changed = to ==
> Update Text Sensor causing compile issues

- src/docs/devices/TreatLife-DS02F/index.md
* Clarify that the baudrate warning is OK to ignore like the DS03.
* Add caution around desoldering with a heat gun near the black foam light guards
* Tidy up the sample YAML
* Typos in the description
> Update DS02F text and template

- src/docs/devices/Gosund-SP111/index.md
When plug is switch on the red led is turn on, when switch is off the red led is off.
> Gosund SP111 activate red light.

- src/docs/devices/kincony-kc868-a2/index.md
> add KinCony KC868-A2

- src/docs/adding-devices.md
- src/docs/devices/Gosund-SP112/index.md
- src/docs/devices/Sonoff-Basic-DIY-light/index.md
Fixes some errors I caught running `markdownlint-cli` locally.
> Fix markdownlint errors

- src/docs/devices/kincony-kc868-a4s/index.md
> Add KinCony KC868-A4S

- src/docs/devices/KinCony-KC868-ASR/index.md
- src/docs/devices/kincony-kc868-am/index.md
> Add KinCony KC868-ASR

- src/docs/devices/Mirabella-Genio-Wi-Fi-Dimmable-Warm-White-ES-9W-LED-GLS-Bulb/index.md
Uses PWM on 14. Different to previous devices.
> Add Mirabella Mirabella Genio Wi-Fi Dimmable Warm White ES 9W LED GLS Bulb

- src/docs/devices/Smartpoint-Wifi-Smart-Remote-Controller/index.md
Fixed gammarar error in my original write-up. 
I also took the liberty of improving the disassembly documentation after another round of disassembling these devices (if present self can't follow what past self wrote, past self wrote bad docs).
> Fixed Grammar, Improved Disassembly Documentation (Smartpoint Wifi Smart Remote Controller)

- src/components/DeviceData/devicedata.js
- src/components/DeviceLink.js
Addresses: https://github.com/esphome/esphome-devices/pull/443#issuecomment-1545987023
> Fix project URL casing

- src/docs/devices/Shelly-Plus-i4/index.md
updated correct configuration for arduino core
> Update Arduino Core Configuration

- src/docs/devices/Shelly-Bulb-Duo-RGBW/index.md
- src/docs/devices/Shelly-Duo-E27/index.md
Added the web_server option to allow for direct access via IP address
> Added webserver to yaml

- src/docs/devices/Shelly-Vintage-A19/index.md
> Removed duplicate key for api

- src/docs/devices/emporia_smart_plug/main.md
Adding the Emporia Smart Plug with Power Monitoring device. This configuration has been tested on a personal device prior to submitting this PR.
Verification:
- Button: Works
- Red LED: Works
- Relay: Works
- Power monitoring
- Current: Works, verified shunt resistor matches config
- Power: Works
- Voltage: Works
Further Improvements:
- Blue LED control: Present in device but seems to share RX pin. Should illuminate when UART adapter is attached but does not.
- Voltage Validation: Voltage divider value result in reasonable voltage values but not confirmed.
- Daughterboard pinout: All required nets are broken out to the mainboard/daughterboard connection but I didn't document it.
> Adding Emporia Smart Plug main.md

- src/docs/devices/Sonoff-M5/index.md
LED 1 actually connected to separate from Relay GPIO.
> Fix Sonoff M5 1gang

- src/docs/devices/AC-DC-ESP32-Relay-x4/index.md
fix typo in title: Relay not Realy
> Fix title in index.md 

- src/docs/devices/Sinilink-XY-WFUSB-USB-Switch-Relay/index.md
Clarify User function pins. Add comments about pin levels.
> Update Sinilink-XY-WFUSB doc

- src/docs/devices/Athom-Human-Presence-Sensor/index.md
updating example to match as restore_state is now deprecated https://github.com/athom-tech/athom-configs/blob/main/athom-presence-sensor.yaml
> Update Athom Human Presence Sensor (PS01)

- src/docs/devices/LSC-Plug-2578685/index.md
Added information about different versions of the device.
Added config for BK7231N
> Update LSC-Plug-2578685 index.md

- src/docs/devices/Arlec-PC191HA-Plug/index.md
I thought I fixed these few typos in the original PR.  I'm still learning.
> fix typos in Update index.md

- src/docs/devices/Lingan-SWA1/index.md
Added 3 config examples for a switch, fan or light.
> Added Lingan SWA1 device

- src/docs/devices/Arlec-Grid-Connect-Smart-Ceiling-Fan-DCF4002/index.md
Arlec Grid Connect Ceiling Fan and Light combo.  Bit of a weird one, it has an RF remote control that talks to the MCU, which provides status updates to ESPHome.
Confirmed working.
> Created configuration details.  Will provide images of the boards later for context.

- src/docs/devices/Martin-Jerry-US-SS02/index.md
I couldn't find any example of an ESPHome configuration for this switch and had to look up the Tasmota template and come up with corresponding ESPHome yaml. Sharing this with the community to save time for someone else
> Add documentation for Martin Jerry US-SS02 Humidity Sensor Switch

- src/docs/devices/Kogan-Smarterhome-Bladeless-DC-Motor-Turbo-Smart-Fan/index.md
Corrected wrong GPIO's used in YAML
> Corrected wrong GPIO's used in YAML

- src/docs/devices/Nous-A5t/index.md
Added info that it is a Tasmota device and can be flashed with ESPHome.
Also fixed faulty config.
> Add details and fix config

- src/docs/devices/Milfra-MFA05/index.md
This is my first PR so let me know if something doesn't look right.
I wanted to make sure this config was saved outside of a random forum post because I found it very valuable!
> Added Milfra MFA05 device

- src/docs/devices/Orno-Single-Phase-Energy-meter-OR-WE-504/index.md
Hello,
The config for OR-WE-504 does not work (indeed, it's config for 514!).
This PRs proposes the configuration for OR-WE-504.
It has been successfully tested on my device.
Thanks
> Fix OR-WE-504

- src/docs/devices/Sonoff-M5/index.md
Adds advanced config file for Sonoff Switchman M5 3-gang US version.
> adding Sonoff M5 3-gang US version configuration

- src/docs/devices/Sinilink-XY-WFUSB-USB-Switch-Relay/index.md
Just purchased one of these and made some tweaks to the configuration which improved functionality, especially with Home Assistant:
* wifi platform changes - fast_connect and power_save_mode HIGH (device is a lot cooler and maintains stable connectivity)
* Add time/homeassistant platform to enable time sync
* Add ota platform
* Add logger platform
* Add wifi_signal sensor
* Add restart button
* Add restore_from_flash to maintain last relay state on power loss/restore
> Update Sinilink XY-WFUSB

- src/docs/devices/Nous-A5t/index.md
- Make restore_mode a variable
- Update sensors to use throttle after esphome#6095
- The main button switch everything off instead of toggling
- Use above and below instead of lambda with C code
- Try to simplify the template
> Update Nous A5T

- src/docs/devices/DETA-Grid-Connect-Smart-Switch/index.md
Adding config example for 6903HA Series 2 based on Beken chip
> Add Deta 6903HA series 2 config for BK72xx

- src/docs/devices/Shelly-Uni/index.md
Adding ADC multipliers for both ranges (0-15/0-30).
> Add: Shelly Uni ADC multiply

- src/docs/devices/Deta-Grid-Connect-Smart-Fan-Speed-Controller-with-Touch-Light-Switch/index.md
Add information about Deta 6914HA Series 2 with BK72xx
> Add Deta 6914HA Series 2 with BK72xx

- src/docs/devices/Sonoff-S31/index.md
`filters` was tabbed over one too far, would not compile.
> Fix indentation on index.md

- src/docs/devices/LocalBytes-Bulb-RGBCT/index.md
- src/docs/devices/LocalBytes-Smart-Plug/index.md
> Add: LocalBytes Devices

- src/docs/devices/Digitaling-20A-Power-Monitor-RTL8710BX-t102-v1.1/index.md
Removed spaces compared to previous pull request.
> Add Device smartplug Digitaling 20A Power Monitor RTL8710BX t102-v1.1

- src/docs/devices/King-Wall-Switch-3Gang/index.md
Fixed CI - lint on markdown failing
> Add King / Smartlife 3 gang switch.

- src/docs/devices/refoss-p11-plug/index.md
update template to comply with current version of esphome
> Update refoss-p11-plug template

- src/docs/devices/Shelly-Plus-2PM/index.md
Since example configurations were not 100% accurate for the Shelly Plus 2PMs I just bought in Austria, an updated example was added, which additionally examplifies the Shelly Plus 2PM's usage as a window cover control.
> Extend Shelly Plus 2PM with new, differing configuration example

- src/docs/devices/Aoycocr-EU6S/index.md
> add Aoyocr-EU6S

- src/docs/devices/ESP32E-Relay-X8/index.md
Added a helpful comment on how much power this draws.
Also (for me) the LED doesn't need to be inverted.
> Very minor notes on the 8-relay esp32 boards.

- src/docs/devices/Nous-A1t/index.md
Added early_pin_init: false and restore_mode: RESTORE_DEFAULT_ON to the led and the switches to keep the relay from flickering when rebooting or updating.
> Update Nous A1T

- src/docs/devices/Holman-4x34mm-spotlight/index.md
> new device

- src/docs/devices/Gosund-SP112/index.md
Because the new devices SP112 can not be provided with ESPHome out of factory; this is an alternative
> Update index.md - added Alternative for newer devices Gosung SP112

- src/docs/devices/Sonoff-POW-Elite-16a/index.md
- src/docs/devices/Sonoff-POW-Elite-20a/index.md
- src/docs/devices/Sonoff-POW-R1/index.md
- src/docs/devices/Sonoff-RF-Bridge/index.md
I noticed these devices are miscategorized.
> chore: fix types for Sonoff devices

- src/docs/devices/LoraTap-SC500W/index.md
- src/docs/devices/Sonoff-POW-Elite-16a/index.md
- src/docs/devices/Sonoff-POW-Elite-20a/index.md
- src/docs/devices/Sonoff-POW-R1/index.md
- src/docs/devices/Sonoff-RF-Bridge/index.md
- src/docs/devices/Sonoff-THR316/index.md
- src/docs/devices/Sonoff-THR320D/index.md
Added difficulty metadata in few devices
> add difficulty in some devices

- src/docs/devices/KMP-PRODINo-ESP32EX/index.md
- src/docs/devices/KinCony-KC868-A8/index.md
- src/docs/devices/KinCony-KC868-AIO/index.md
- src/docs/devices/KinCony-KC868-ASR/index.md
- src/docs/devices/KinCony-KC868-Uair/index.md
- src/docs/devices/Sonoff-THR320D/index.md
esphome 2024.6 replaced dallas component with one_wire and replace dallas sensors with dallas_temp.
https://esphome.io/changelog/2024.6.0.html#wire
This CL applies those changes to the sample yaml.
Please squash the commits in this PR when merging, I am using the editor and cannot do that for myself.
> Update Dallas sensor configuration to match recent changes

- src/docs/devices/Mirabella-Door-Window-Sensor/index.md
> Update URL to Mirabella Genio Door & Window sensor product page

- src/docs/devices/DETA-Grid-Connect-Smart-Switch/index.md
> add pin out table

- src/docs/devices/Apollo-Automation-AIR-1/index.md
- src/docs/devices/Apollo-Automation-MSR-1/index.md
- src/docs/devices/Apollo-Automation-MSR-2/index.md
- src/docs/devices/Apollo-Automation-MTR-1/index.md
Updated the Apollo devices with the Made For ESPHome approval
> Add Made For ESPHome To Apollo Devices

- src/docs/devices/KinCony-KC868-A6/index.md
The config on the page belongs to some other device. The corrected and tested configuration is here.
> Correction of Kincony KC868-A6 configuration

- src/docs/devices/LoraTap-SC411WSC-CurtainSwitch/index.md
> new device SC411WSC

- src/docs/devices/Tuya-2-Gang-Switch-Socket/index.md
> Tuya 2 Gang Switch Socket

- src/docs/devices/DIY-Smart_Switch/index.md
Will add photo after. still not sure how
> New smart relay

- src/docs/devices/Arlec-PC191HA-Plug/index.md
Configuration for swapping BK7231 with ESP8285.
> Added configuration for swapping to ESP8285 module and fixed my spacing

- src/docs/devices/TreatLife-DS02F/index.md
Add correct RX /TX pins for ESP32-C3F chips
> Update Treatlife DS02F

- src/docs/devices/ESP32E-Relay-X8/index.md
Small minor typo fix- Changed "Realy" in title to "Relay"
> Minor - Fixed Typo in ESP32E-Relay-X8 index.md

- src/docs/devices/Duux-Whisper-Flex-UItimate-Smart-Fan-DXCF14/index.md
Correction of the copy and paste mistake by @GraafG 
I have removed the duplicate entries that were copied from Duux Whisper Flex template.
> Correct copy and paste mistake for Duux Whisper Flex Ultimate

- src/docs/devices/DETA-Grid-Connect-Smart-Dimmer-Switch/index.md
Updated information as Dimmer 6910HA can now be flashed OTA using cloudCutter
> Update index.md Dimmer 6910HA can now be flashed OTA

- src/docs/devices/Tuya-DY-RQ400A-Combustible-Gas-Alarm/index.md
I have added the platform: esphome parameter to the ota component to comply with the standard of the latest versions of ESPHome
> Update index.md to the latest version of ESPHOme

- src/docs/devices/Gosund-SP211-BK72XX/index.md
> Fix unclosed yaml section

- src/components/search/index.js
- src/components/search/search-result.js
- src/components/search/use-click-outside.js
These warnings were raised when running `npm start`.
> Fix some Javascript warnings

- src/docs/devices/Sonoff-TH10/index.md
Added a refernce to GPIO-14 Sensor
> Update index.md added Sensor - GPIO-14

- .markdownlintrc
As discussed on [discord](https://discord.com/channels/429907082951524364/1092224152305418250/1300312347264680007). Relates to #896.
> Allow collapsable markdown elements

- src/docs/devices/Dingtian-DT-R016/index.md
Added DT-R016 Configuration
Added Dingtian DT-R016
> Add DT-R016

- src/docs/devices/Sonoff-BASIC-R2-v1.4/index.md
Light must be turned on/off using `light` and not `switch`.
Also, `ota:` needs a platform specified.
> Sonoff Basic R2 example correction

- src/docs/devices/Gosund-SP112/index.md
- align with [SP111 template](https://github.com/esphome/esphome-devices/blob/main/src/docs/devices/Gosund-SP111/index.md)
- add total daily counter
- add sensors
> align with SP111, use devicename, add sensors and total_energy

- src/docs/devices/Shelly-1-Mini-Gen3/index.md
- src/docs/devices/Shelly-1PM-Mini-Gen3/index.md
- src/docs/devices/Shelly-PM-Mini-Gen3/index.md
- src/docs/devices/Shelly-i4-Gen3/index.md
- Remove secrets
- Remove invalid crc config
- formatting
> Update Shelly Gen3 configs

- src/docs/devices/MQ-7/index.md
I made a PCB for the heater for those that prefer making a new PCB rather than modifying the existing one.
> Add link to PCB heater mod

- src/docs/devices/SelfIY-Ring-by-Nerdiy/index.md
Initial commit for device creation of SelfIY Ring.
> Create index.md for SelfIY Ring by Nerdiy.de

- src/docs/devices/Hama-Wifi-LED-Lamp-RGBW-10W-806lm/index.md
- src/docs/devices/LEDVANCE-E27-RGBW/index.md
> fix: rename bk72xx from bk27xx

- src/docs/devices/smartpad-em32-smart-plug/index.md
> Mark SmartPad EM32 Smart Plug as Made for ESPHome

- src/docs/devices/SelfIY-Ring-by-Nerdiy/index.md
Aprooved for "made for Esphome".
> Mark Nerdiy's SelfIY Ring as Made for ESPHome

- src/docs/devices/Petkit-Fresh-Element-Solo-Pet-Feeder/index.md
- Update docs for Petkit Fresh Element Solo pet feeder for new board variant.
- Higher resolution of wiring diagram for original variant wiring diagram from linked reddit comment.
> Update docs for Petkit Fresh Element Solo pet feeder for new board variant.

- src/docs/devices/Shelly-1/index.md
The previous example `.yaml` configs in this documentation article references had support removed in [2025.02](https://esphome.io/changelog/2025.2.0.html). 
These updated configuration examples in this PR ensure that new users are able to get started with minimal confusion.
> Shelly 1 documentation: make platform configuration functional with changes in 2025.02

- src/docs/devices/LinkGear-CO2-Ampel-ECA1/index.md
Just changed the project URL to the correct one. The old one was moved and 404s.
> Update project URL on LG-ECA1 (old one 404s)

- src/docs/devices/Alfawise-SJ-7/index.md
Updated for ESPHOME 2025.2.0 and later
https://esphome.io/guides/contributing#a-note-about-custom-components
- [?] The first configuration provided should be **hardware definitions only**.
> Device ALFAWISE SJ-7 updated for ESPHOME 2025.2.0 and later

- src/docs/devices/SiloCityLabs-AirQuality/index.md
Initial commit for device creation of SiloCityLabs Air Quality Monitor.
> Added SiloCityLabs Air Quality Monitor

- src/docs/devices/Gosund-SP111/index.md
> adapt new syntax

- src/docs/devices/GL-iNet-GL-S10/index.md
The correct file format is jpg.
> fix image2

- src/docs/devices/Norvi-IIOT-AE02-I/index.md
> Add Norvi IIOT ESP32-PLC

- src/docs/devices/Sonoff-Dual-R3/index.md
missing unit - was not compiling
> missing unit

- src/docs/devices/Sonoff-S26/index.md
> Added instructions of putting the device into flash mode

- src/docs/devices/Feit-DIMSMART-3-CAN/index.md
Made the thing a `light:` rather than a `switch:`.  After this commit I'll remove other things that are not hardware specific.
> Changed yaml to be a dimmer rather than a switch

- .github/workflows/made-for-esphome.yml
> [made for esphome] Check for capital T too

- .github/made-for-esphome-checklist.md
> Add links to docs to checklist template

- .github/workflows/made-for-esphome.yml
> Request changes rather than simply comment

- src/docs/devices/ESP32-Relay-X16/index.md
> Update ESP32-Relay-X16 description and configuration

- .github/copilot-instructions.md
> Add initial copilot instructions

- .github/copilot-instructions.md
> More copilot instructions

- src/docs/devices/Sonoff-M5/index.md
This would have saved me two hrs of debug
> Sonoff M5 add note about usb-uart power supply

- src/docs/devices/Shelly-Plus-2PM-Gen-4/index.md
- [*] New device
- [*] There are no passwords or secrets references in any examples. 
- [*] The `wifi` or `ethernet` block has no static / manual ip address specified.
- [*] The first configuration provided should be **hardware definitions only**.
> Add shelly 2pm gen 4

- src/docs/devices/shelly-1pm-gen-4/index.md
add new device
- [*] New device
- [*] There are no passwords or secrets references in any examples. 
- [*] The `wifi` or `ethernet` block has no static / manual ip address specified.
- [*] The first configuration provided should be **hardware definitions only**.
> Shelly 1pm gen 4
